/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/metas.glb -o src/components/Logo3dm.jsx -k -K -r -s public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LogoTdm(props) {
  const { nodes, materials } = useGLTF('./models/metas.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube" castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[2.694, 3.438, 0.4]} scale={[0.655, 1, 0.5]} />
        <mesh name="Cube001" castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-2.495, 2.859, 0.4]} rotation={[0, 0, -Math.PI]} scale={[0.655, 1, 0.5]} />
        <mesh name="Cube002" castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[0, 3.2, 0.4]} />
        <mesh name="Cube004" castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials['Material.001']} position={[2.603, 2.043, 0.4]} rotation={[0, 0, 3.14]} />
        <mesh name="Cube005" castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials['material one']} position={[0, 3.2, 0.4]} />
        <mesh name="Cube006" castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials.second} position={[-0.458, 4.046, 0.4]} rotation={[0, 0, -0.051]} />
        <mesh name="Cube007" castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials['material one']} position={[-1.001, 2.831, 0.4]} scale={0.976} />
        <mesh name="Cube008" castShadow receiveShadow geometry={nodes.Cube008.geometry} material={materials.second} position={[-0.387, 3.297, 0.4]} rotation={[0, 0, -0.043]} scale={1.069} />
        <mesh name="Cube009" castShadow receiveShadow geometry={nodes.Cube009.geometry} material={materials['material one']} position={[-0.556, 2.332, 0.4]} rotation={[0, 0, -1.176]} />
        <mesh name="Cube010" castShadow receiveShadow geometry={nodes.Cube010.geometry} material={materials.second} position={[0.357, 3.463, 0.4]} rotation={[0, 0, -2.071]} scale={1.069} />
        <mesh name="Cube011" castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials['Material.006']} position={[1.135, 3.129, 0.4]} rotation={[0, 0, -2.071]} scale={1.069} />
        <mesh name="Cube012" castShadow receiveShadow geometry={nodes.Cube012.geometry} material={materials['material one']} position={[0.193, 2.005, 0.4]} rotation={[0, 0, -1.108]} scale={1.069} />
        <mesh name="Cube013" castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials['Material.006']} position={[0.268, 4.204, 0.4]} rotation={[0, 0, -2.071]} scale={1.069} />
        <mesh name="Cube014" castShadow receiveShadow geometry={nodes.Cube014.geometry} material={materials['Material.006']} position={[1.05, 3.874, 0.4]} rotation={[0, 0, -2.071]} scale={1.069} />
        <mesh name="Cube015" castShadow receiveShadow geometry={nodes.Cube015.geometry} material={materials.second} position={[0.814, 2.463, 0.4]} rotation={[0, 0, -1.108]} scale={1.069} />
        <mesh name="Cube016" castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.second} position={[0.042, 2.795, 0.4]} rotation={[0, 0, -1.108]} scale={1.069} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/metas.glb')
